### ISSUE TITLE
M4 - Mina merkle tree hasher and merger implementation

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/mina-rs#155] opened 2022-02-10 03:59 UTC
**Task summary**

- Implement hasher and merger for mina merkle tree
- Parity tests

**Specification reference**

- 

**Other information and links**

**Comment by creativcoder** [comment] 2022-03-28 05:11
closing this, duplicate of: https://github.com/ChainSafe/mina-rs/issues/156

**Closed by creativcoder** 2022-03-28 05:11 UTC
